version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx-jeg
        restart: unless-stopped
        tty: true
        ports:
            - "8001:80"
        volumes: 
            - ./jeg-learning-hub:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        image: mysql:5.7.22
        container_name: mysql-jeg
        restart: unless-stopped
        tty: true
        ports: 
            - "4306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: laravel_docker
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-jeg
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./jeg-learning-hub:/var/www/app
        ports: 
            - "9000:9000"
        networks: 
            - laravel